-- Dataset real de coloquialismos España <-> Chile (generado desde
-- colloquialismos_espana_chile.csv). Reemplazable/ampliable sin tocar
-- código: basta con insertar, editar o borrar filas en `vocabulario`.
insert into vocabulario (slug, slang_es, slang_cl, definicion, categoria, tipo_gramatical) values
  ('pijo', 'pijo, pija', 'cuico, cuica', 'Persona de clase alta o que imita afectadamente sus gustos, ropa, modales y forma de hablar. Despectivo o burlón.', 'Personas y tipos sociales', 'sustantivo'),
  ('cani', 'cani, choni', 'flaite', 'Joven de barrio popular asociado a una estética llamativa (chándal, gorra, joyas) y a actitudes agresivas o delictivas. Despectivo.', 'Personas y tipos sociales', 'sustantivo'),
  ('macarra', 'macarra, chulo de barrio', 'choro (agresivo), malandra', 'Persona bravucona y pendenciera que intimida o busca pelea.', 'Personas y tipos sociales', 'sustantivo'),
  ('chaval', 'chaval, chavala', 'cabro, cabra, lolo, lola', 'Niño, muchacho o persona joven.', 'Personas y tipos sociales', 'sustantivo'),
  ('crio', 'crío, cría, chiquillo, renacuajo', 'cabro chico, cabra chica, pendejo (no insultante en Chile)', 'Niño pequeño; también adulto que se comporta de forma infantil.', 'Personas y tipos sociales', 'sustantivo'),
  ('bebe', 'bebé, nene', 'guagua', 'Bebé, niño de pecho.', 'Familia', 'sustantivo'),
  ('tio', 'tío, tía (persona cualquiera)', 'gallo, galla, loco (popular)', 'Forma informal de referirse a un hombre o mujer cualquiera: ''ese tío'', ''ese gallo''.', 'Personas y tipos sociales', 'sustantivo'),
  ('tio-1', 'tío, tía, bro (vocativo entre amigos)', 'weón, weona (huevón) (vulg. según tono)', 'Vocativo de confianza entre amigos; en Chile, con otro tono, es insulto.', 'Amistad y trato social', 'sustantivo'),
  ('colega', 'colega, tronco, compi', 'socio, compadre, compa, hermano', 'Amigo o compañero; también vocativo amistoso.', 'Amistad y trato social', 'sustantivo'),
  ('amigo-del-alma', 'amigo del alma, íntimo', 'yunta', 'Amigo íntimo, inseparable.', 'Amistad y trato social', 'sustantivo'),
  ('la-pena', 'la peña, la basca, la panda, la cuadrilla', 'la gallada, la patota, el grupo', 'Grupo de amigos o de gente con la que se sale.', 'Amistad y trato social', 'sustantivo'),
  ('pibon', 'pibón, tía buena, tío bueno, estar como un tren', 'mina rica, mino, minón, estar como quiere, estar rico', 'Persona muy atractiva físicamente.', 'Amor y relaciones', 'sustantivo'),
  ('estar-de-buen-ver', 'estar de buen ver', 'estar potable', 'Ser razonablemente atractivo. Ojo: en España ''potable'' significa ''aceptable, pasable''.', 'Amor y relaciones', 'expresión verbal'),
  ('chorbo', 'chorbo, chorba, mi chico, mi chica', 'pololo, polola', 'Novio o novia, pareja estable sin estar casados.', 'Amor y relaciones', 'sustantivo'),
  ('salir-con-alguien', 'salir con alguien, ser novios', 'pololear', 'Mantener una relación de noviazgo.', 'Amor y relaciones', 'verbo'),
  ('noviazgo', 'noviazgo, relación', 'pololeo', 'Relación amorosa de pareja estable no matrimonial.', 'Amor y relaciones', 'sustantivo'),
  ('ligue', 'ligue, rollo, follamigo (vulg.)', 'andante, pinche, amigo con ventaja', 'Persona con la que se tiene una relación amorosa o sexual informal y sin compromiso.', 'Amor y relaciones', 'sustantivo'),
  ('ligar', 'ligar, pillar cacho', 'pinchar, engrupir', 'Conseguir conquistar a alguien o tener un encuentro romántico.', 'Amor y relaciones', 'verbo'),
  ('tirar-los-tejos', 'tirar los tejos, tirar la caña', 'jotear, tirarse al dulce', 'Intentar seducir o coquetear con alguien.', 'Amor y relaciones', 'verbo'),
  ('baboso', 'baboso, pesado (que liga)', 'jote', 'Persona insistente y algo pesada al coquetear.', 'Amor y relaciones', 'sustantivo'),
  ('ligon', 'ligón, mujeriego, golfo', 'lacho, picaflor', 'Persona que coquetea o tiene relaciones con muchas personas.', 'Amor y relaciones', 'sustantivo'),
  ('calzonazos', 'calzonazos', 'macabeo', 'Hombre dominado por su pareja.', 'Amor y relaciones', 'sustantivo'),
  ('pagafantas', 'pagafantas', null, 'Chico que invita y atiende a una chica esperando una relación que no llega.', 'Amor y relaciones', 'sustantivo'),
  ('sujetavelas', 'sujetavelas, carabina', 'violinista, tocar el violín', 'Persona que acompaña a una pareja y les estorba.', 'Amor y relaciones', 'sustantivo'),
  ('enrollarse', 'enrollarse, liarse, morrearse', 'atracar, agarrar, darse besos', 'Besarse apasionadamente.', 'Amor y relaciones', 'verbo'),
  ('meter-mano', 'meter mano, sobar', 'correr mano', 'Tocar o acariciar a alguien con intención sexual.', 'Amor y relaciones', 'verbo'),
  ('estar-colado', 'estar colado, estar pillado por alguien', 'estar enganchado, estar agarrado, estar hasta las patas', 'Estar muy enamorado o encaprichado.', 'Amor y relaciones', 'expresión verbal'),
  ('dar-calabazas', 'dar calabazas', 'dar filo, no pescar, dejar en visto', 'Rechazar a alguien que te pretende.', 'Amor y relaciones', 'expresión verbal'),
  ('dejar', 'dejar, cortar con alguien', 'patear, cortar, terminar', 'Poner fin a una relación de pareja.', 'Amor y relaciones', 'verbo'),
  ('poner-los-cuernos', 'poner los cuernos', 'poner el gorro, cagar (vulg.), gorrear', 'Ser infiel a la pareja.', 'Amor y relaciones', 'expresión verbal'),
  ('cornudo', 'cornudo', 'cachudo, cornudo', 'Persona a la que su pareja le es infiel.', 'Amor y relaciones', 'sustantivo'),
  ('hacer-de-celestina', 'hacer de celestina', 'hacer gancho', 'Presentar a dos personas para que formen pareja.', 'Amor y relaciones', 'expresión verbal'),
  ('follar', 'follar, echar un polvo (vulg.)', 'culiar, tirar (vulg.)', 'Tener relaciones sexuales.', 'Amor y relaciones', 'verbo'),
  ('carino', 'cariño, cari, cielo, gordi', 'mi amor, guatón, guatona, gordi', 'Apelativos cariñosos para la pareja o seres queridos.', 'Amor y relaciones', 'sustantivo'),
  ('mimar', 'mimar, hacer mimos', 'regalonear, hacer nanai', 'Dar cariño, consentir o acurrucar a alguien.', 'Familia', 'verbo'),
  ('mimado', 'mimado, consentido, niño de mamá', 'regalón, regalona', 'Persona consentida, a quien se le da todo.', 'Familia', 'adjetivo'),
  ('el-pequeno-de-la-casa', 'el pequeño de la casa, el benjamín', 'el concho', 'El hijo menor de una familia.', 'Familia', 'sustantivo'),
  ('los-viejos', 'los viejos, los puretas (los padres)', 'los viejos, mis viejos', 'Los padres, dicho con confianza.', 'Familia', 'sustantivo'),
  ('yayo', 'yayo, yaya', 'tata, abue', 'Abuelo o abuela, en lenguaje familiar.', 'Familia', 'sustantivo'),
  ('chacha', 'chacha, chica de la limpieza', 'nana', 'Empleada doméstica que limpia o cuida niños.', 'Familia', 'sustantivo'),
  ('empollon', 'empollón, empollona', 'mateo, matea, ñoño', 'Estudiante muy aplicado; en Chile ''ñoño'' también es ''nerd''.', 'Trabajo y estudio', 'sustantivo'),
  ('friki', 'friki', 'ñoño, freak', 'Persona apasionada por aficiones consideradas raras (cómics, videojuegos, ciencia ficción).', 'Personas y tipos sociales', 'sustantivo'),
  ('pelota', 'pelota, pelotillero, lameculos (vulg.)', 'patero, chupamedias, sobaco ilustrado', 'Persona aduladora con superiores para obtener favores.', 'Personas y tipos sociales', 'sustantivo'),
  ('hacer-la-pelota', 'hacer la pelota', 'hacer la pata, chupar las medias', 'Adular a alguien para ganarse su favor.', 'Personas y tipos sociales', 'expresión verbal'),
  ('chivato', 'chivato, acusica', 'sapo, soplón', 'Persona que delata o cuenta lo que otros hacen.', 'Personas y tipos sociales', 'sustantivo'),
  ('cotilla', 'cotilla, chafardero', 'copuchento, cahuinero, pelador', 'Persona chismosa que difunde rumores.', 'Chismes, bromas y mentiras', 'sustantivo'),
  ('cotilleo', 'cotilleo, salseo (juv.), chisme', 'copucha, cahuín', 'Chisme, rumor o drama sobre otros.', 'Chismes, bromas y mentiras', 'sustantivo'),
  ('cotillear', 'cotillear, chismorrear', 'copuchar, cahuinear', 'Contar o comentar chismes.', 'Chismes, bromas y mentiras', 'verbo'),
  ('fisgar', 'fisgar, cotillear (mirar)', 'sapear', 'Mirar o espiar con curiosidad lo que hacen otros.', 'Chismes, bromas y mentiras', 'verbo'),
  ('poner-verde', 'poner verde, poner a parir, despellejar', 'pelar', 'Hablar mal de alguien a sus espaldas.', 'Chismes, bromas y mentiras', 'verbo'),
  ('bocazas', 'bocazas', 'hocicón, hocicona', 'Persona que no guarda secretos o habla de más.', 'Personas y tipos sociales', 'sustantivo'),
  ('irse-de-la-lengua', 'irse de la lengua', 'caérsele el cassette, hociconear', 'Contar algo que no se debía decir.', 'Chismes, bromas y mentiras', 'expresión verbal'),
  ('tacano', 'tacaño, rata, agarrado, roñoso', 'apretado, codo, mano de guagua', 'Persona avara que no quiere gastar.', 'Dinero', 'adjetivo'),
  ('gorron', 'gorrón', 'bolsero', 'Persona que siempre pide o vive a costa de los demás.', 'Dinero', 'sustantivo'),
  ('gorronear', 'gorronear', 'bolsear', 'Pedir o consumir a costa de otros.', 'Dinero', 'verbo'),
  ('caradura', 'caradura, jeta, tener morro', 'patudo, fresco, barsa', 'Persona descarada y sinvergüenza.', 'Personas y tipos sociales', 'sustantivo'),
  ('chulo', 'chulo, creído, flipado', 'creído, agrandado, creerse la muerte', 'Persona engreída y presumida.', 'Personas y tipos sociales', 'adjetivo'),
  ('fardar', 'fardar, chulear, vacilar', 'cachiporrearse, creerse la muerte', 'Presumir o jactarse de algo.', 'Personas y tipos sociales', 'verbo'),
  ('listillo', 'listillo, sabelotodo, sobrao', 'sabelotodo, sobrado', 'Persona que cree saberlo todo y lo hace notar.', 'Personas y tipos sociales', 'sustantivo'),
  ('cunado', 'cuñado, cuñao', 'opinólogo (aprox.)', 'Persona que opina de todo con seguridad y sin saber; en Chile ''opinólogo'' es más mediático.', 'Personas y tipos sociales', 'sustantivo'),
  ('pringado', 'pringado, pardillo', 'gil, pavo, ganso', 'Persona ingenua que se deja engañar o carga con lo peor.', 'Personas y tipos sociales', 'sustantivo'),
  ('melon', 'melón, memo, cenutrio, besugo', 'weón (vulg.), aweonao (vulg.), leso', 'Persona tonta o torpe.', 'Personas y tipos sociales', 'sustantivo'),
  ('gilipollas', 'gilipollas, capullo (vulg.)', 'weón, saco de weas (vulg.)', 'Insulto común: persona estúpida o que actúa mal.', 'Personas y tipos sociales', 'sustantivo'),
  ('empanado', 'empanado, en Babia, en las nubes, en la parra', 'volado, pajarón, estar en otra', 'Distraído, despistado, que no se entera.', 'Personas y tipos sociales', 'adjetivo'),
  ('chalado', 'chalado, pirado, como una cabra, majara', 'loco, enfermo del mate, peinar la muñeca, piteado', 'Persona loca o muy excéntrica.', 'Personas y tipos sociales', 'adjetivo'),
  ('cursi', 'cursi, repipi', 'siútico, siútica', 'Persona que pretende elegancia o refinamiento de forma ridícula.', 'Personas y tipos sociales', 'adjetivo'),
  ('hortera', 'hortera', 'cuma, picante, rasca', 'De mal gusto, ordinario en estética o comportamiento.', 'Valoración y aprobación', 'adjetivo'),
  ('paleto', 'paleto, cateto, pueblerino', 'huaso (despect.), provinciano', 'Persona rústica o de campo, poco refinada. Ojo: ''catete'' en Chile es ''pesado''.', 'Personas y tipos sociales', 'sustantivo'),
  ('facha', 'facha', 'facho', 'Persona de ideas fascistas o de extrema derecha. Despectivo.', 'Personas y tipos sociales', 'sustantivo'),
  ('rojo', 'rojo, rojillo', 'comunacho, zurdo (despect.)', 'Persona de izquierdas, dicho de forma despectiva o burlona.', 'Personas y tipos sociales', 'sustantivo'),
  ('guiri', 'guiri', 'gringo', 'Extranjero o turista, sobre todo anglosajón o del norte de Europa.', 'Personas y tipos sociales', 'sustantivo'),
  ('madero', 'madero, poli, pasma, bofia', 'paco, paca', 'Policía uniformado; en Chile, carabinero.', 'Delincuencia y policía', 'sustantivo'),
  ('secreta', 'secreta', 'tira, rati', 'Policía de investigación o de paisano.', 'Delincuencia y policía', 'sustantivo'),
  ('chorizo', 'chorizo, mangante, ratero', 'ladrón, choro, patomalo', 'Ladrón.', 'Delincuencia y policía', 'sustantivo'),
  ('carterista', 'carterista, descuidero', 'lanza', 'Ladrón que roba carteras o joyas por sorpresa.', 'Delincuencia y policía', 'sustantivo'),
  ('tiron-robo', 'tirón (robo)', 'lanzazo', 'Robo rápido arrebatando algo a alguien.', 'Delincuencia y policía', 'sustantivo'),
  ('atracador', 'atracador', 'cogotero', 'Asaltante que amenaza a la víctima, a menudo con arma blanca.', 'Delincuencia y policía', 'sustantivo'),
  ('mangar', 'mangar, birlar, chorizar', 'güiñar, pelar, cooperar (irónico)', 'Robar o hurtar algo.', 'Delincuencia y policía', 'verbo'),
  ('trullo', 'trullo, talego, chirona', 'cana, la peni', 'Cárcel.', 'Delincuencia y policía', 'sustantivo'),
  ('barrio-chungo', 'barrio chungo, barrio marginal', 'población, la pobla', 'Barrio popular o marginal.', 'Delincuencia y policía', 'sustantivo'),
  ('okupa', 'okupa', 'toma, los de la toma', 'Ocupación ilegal de un terreno o vivienda, o las personas que la ocupan.', 'Delincuencia y policía', 'sustantivo'),
  ('perroflauta', 'perroflauta', 'hippie, artesa', 'Joven de estética alternativa o hippie. Despectivo en España.', 'Personas y tipos sociales', 'sustantivo'),
  ('manitas', 'manitas', 'maestro chasquilla', 'Persona que arregla de todo; en Chile, con matiz de arreglo improvisado.', 'Trabajo y estudio', 'sustantivo'),
  ('chapuza', 'chapuza, chapucero', 'hecho a la chilena, atado con alambre', 'Trabajo mal hecho o improvisado.', 'Trabajo y estudio', 'adjetivo'),
  ('mosquita-muerta', 'mosquita muerta', 'cara de yo no fui', 'Persona que aparenta inocencia pero no lo es.', 'Personas y tipos sociales', 'sustantivo'),
  ('aguafiestas', 'aguafiestas, cortarrollos', 'corta onda, mata pasiones', 'Persona que estropea la diversión de los demás.', 'Personas y tipos sociales', 'sustantivo'),
  ('enchufado', 'enchufado', 'apitutado', 'Persona que consigue algo gracias a contactos o influencias.', 'Trabajo y estudio', 'adjetivo'),
  ('enchufe', 'enchufe', 'pituto', 'Contacto o influencia para lograr algo, sobre todo un trabajo.', 'Trabajo y estudio', 'sustantivo'),
  ('pololito', null, 'pololito', 'Trabajo extra, esporádico o informal para ganar dinero.', 'Trabajo y estudio', 'sustantivo'),
  ('curro', 'curro', 'pega', 'Trabajo, empleo.', 'Trabajo y estudio', 'sustantivo'),
  ('currar', 'currar, pringar', 'camellar, trabajar', 'Trabajar, especialmente con esfuerzo.', 'Trabajo y estudio', 'verbo'),
  ('deslomarse', 'deslomarse, currar como un burro', 'sacarse la cresta trabajando, trabajar como chino', 'Trabajar muchísimo.', 'Trabajo y estudio', 'expresión verbal'),
  ('escaquearse', 'escaquearse, escurrir el bulto', 'sacar la vuelta, sacarle el poto a la jeringa', 'Evitar el trabajo o una responsabilidad.', 'Trabajo y estudio', 'expresión verbal'),
  ('plegar-catalanismo', 'plegar (catalanismo)', 'salir de la pega', 'Terminar la jornada laboral.', 'Trabajo y estudio', 'expresión verbal'),
  ('estar-en-el-paro', 'estar en el paro', 'estar cesante, estar sin pega', 'Estar desempleado.', 'Trabajo y estudio', 'expresión verbal'),
  ('jefe', 'jefe, mandamás, el baranda (ant.)', 'jefe, patrón', 'Persona que manda en un trabajo.', 'Trabajo y estudio', 'sustantivo'),
  ('puente', 'puente', 'fin de semana largo, sándwich (día entre feriados)', 'Días libres que se juntan con un festivo.', 'Cantidad, tiempo e intensidad', 'sustantivo'),
  ('mileurista', 'mileurista', null, 'Persona joven con sueldo bajo, de unos mil euros.', 'Dinero', 'sustantivo'),
  ('pasta', 'pasta, guita, pelas, money', 'plata, billete, lucas, money', 'Dinero.', 'Dinero', 'sustantivo'),
  ('pavo', 'pavo, napo (un euro)', 'luca (mil pesos)', 'Unidad monetaria coloquial: en España ''pavo'' es un euro; en Chile ''luca'' son mil pesos.', 'Dinero', 'sustantivo'),
  ('quina', null, 'quina', 'Moneda de quinientos pesos chilenos.', 'Dinero', 'sustantivo'),
  ('kilo-millon', 'kilo (millón)', 'palo, melón', 'Un millón de unidades de moneda.', 'Dinero', 'sustantivo'),
  ('calderilla', 'calderilla', 'chauchas', 'Monedas sueltas de poco valor; poco dinero.', 'Dinero', 'sustantivo'),
  ('estar-pelado', 'estar pelado, sin blanca, a dos velas, tieso', 'andar pato, estar pato, estar seco', 'No tener dinero.', 'Dinero', 'expresión verbal'),
  ('forrado', 'forrado, podrido de pasta', 'forrado, podrido en plata', 'Muy rico.', 'Dinero', 'adjetivo'),
  ('hacer-un-bote', 'hacer un bote', 'hacer una vaca', 'Juntar dinero entre varios para comprar algo.', 'Dinero', 'expresión verbal'),
  ('a-pachas', 'a pachas, a medias', 'a medias, mitad y mitad', 'Pagar algo entre dos a partes iguales.', 'Dinero', 'expresión adverbial'),
  ('estirarse', 'estirarse, invitar', 'rajarse', 'Invitar pagando por otros con generosidad. Ojo: en España ''rajarse'' es ''echarse atrás''.', 'Dinero', 'verbo'),
  ('generoso', 'generoso, espléndido', 'rajado', 'Persona que invita y gasta con generosidad.', 'Dinero', 'adjetivo'),
  ('hacer-un-simpa', 'hacer un simpa', 'hacer perro muerto', 'Irse de un local sin pagar la cuenta.', 'Dinero', 'expresión verbal'),
  ('timo', 'timo, estafa, tocomocho', 'cuento del tío, estafa', 'Engaño para sacar dinero a alguien.', 'Dinero', 'sustantivo'),
  ('timador', 'timador, trilero', 'chanta, cuentero', 'Estafador; persona poco confiable.', 'Dinero', 'sustantivo'),
  ('clavar', 'clavar, ¡qué clavada!, sablazo', 'te vieron la cara, te cagaron (vulg.)', 'Cobrar un precio abusivo.', 'Dinero', 'expresión verbal'),
  ('costar-un-rinon', 'costar un riñón, un ojo de la cara', 'costar un ojo de la cara', 'Ser muy caro.', 'Dinero', 'expresión verbal'),
  ('tirado', 'tirado, de saldo', 'regalado, barateli', 'Muy barato.', 'Dinero', 'adjetivo'),
  ('chollo', 'chollo', 'ganga, regalado', 'Cosa buena conseguida a muy bajo precio o con poco esfuerzo.', 'Dinero', 'sustantivo'),
  ('picada', null, 'picada', 'Local barato y sencillo donde se come o compra muy bien.', 'Comida y bebida', 'sustantivo'),
  ('cutre', 'cutre', 'rasca, charcha, penca', 'De mala calidad, pobre o descuidado.', 'Valoración y aprobación', 'adjetivo'),
  ('de-imitacion', 'de imitación, de los chinos', 'marca chancho', 'Producto falsificado o de calidad dudosa.', 'Valoración y aprobación', 'adjetivo'),
  ('trasto', 'trasto, cacharro', 'cachureo', 'Objeto viejo o inútil que se guarda.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('chisme', 'chisme, cosa, cacharro (comodín)', 'cuestión, la wea (vulg.)', 'Palabra comodín para cualquier objeto cuyo nombre no se dice.', 'Muletillas y expresiones', 'sustantivo'),
  ('tocho', 'tocho, mamotreto', 'ladrillo', 'Libro o texto muy largo y pesado.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('marron', 'marrón', 'cacho', 'Problema o tarea desagradable que le toca a alguien.', 'Problemas, líos y errores', 'sustantivo'),
  ('comerse-el-marron', 'comerse el marrón, pagar el pato', 'quedarse con el cacho, pagar el pato', 'Cargar con la culpa o la consecuencia de algo.', 'Problemas, líos y errores', 'expresión verbal'),
  ('follon', 'follón, lío, movida', 'atado, boche, cahuín', 'Problema, enredo o alboroto.', 'Problemas, líos y errores', 'sustantivo'),
  ('complicarse', 'complicarse, liarse', 'hacerse atado, enrollarse', 'Complicar una situación más de lo necesario.', 'Problemas, líos y errores', 'verbo'),
  ('montar-un-pollo', 'montar un pollo, montar un número, liarla parda', 'dejar la cagada (vulg.), dejar la escoba, armar un show', 'Armar un escándalo.', 'Problemas, líos y errores', 'expresión verbal'),
  ('armarse-la-gorda', 'armarse la gorda', 'quedar la cagada (vulg.), quedar la escoba, quedar la crema', 'Producirse un gran escándalo o caos.', 'Problemas, líos y errores', 'expresión verbal'),
  ('meter-la-pata', 'meter la pata, cagarla (vulg.)', 'cagarla, embarrarla, mandarse un condoro', 'Cometer un error.', 'Problemas, líos y errores', 'expresión verbal'),
  ('metedura-de-pata', 'metedura de pata, cagada (vulg.)', 'condoro, embarrada, cagada', 'Error grave o vergonzoso.', 'Problemas, líos y errores', 'sustantivo'),
  ('irse-al-garete', 'irse al garete, irse a la mierda (vulg.)', 'chacrearse, funarse', 'Arruinarse un plan o una situación.', 'Problemas, líos y errores', 'verbo'),
  ('cargarse-algo', 'cargarse algo, petar', 'echar a perder, hacer pebre', 'Romper o estropear algo.', 'Problemas, líos y errores', 'expresión verbal'),
  ('hecho-polvo', 'hecho polvo, hecho trizas, hecho un cristo', 'hecho bolsa, hecho pebre', 'Destrozado física o anímicamente; muy dañado.', 'Problemas, líos y errores', 'adjetivo'),
  ('estar-jodido-vulg', 'estar jodido (vulg.), estar apañado', 'estar cagado (vulg.), estar frito', 'Estar en un problema serio.', 'Problemas, líos y errores', 'expresión verbal'),
  ('chungo-dificil', 'chungo (difícil, peligroso)', 'brígido, peludo, turbio', 'Difícil, peligroso o de aspecto dudoso.', 'Problemas, líos y errores', 'adjetivo'),
  ('heavy', 'heavy, fuerte, una pasada', 'cuático, heavy, brígido', 'Algo extremo, exagerado o intenso, para bien o para mal.', 'Cantidad, tiempo e intensidad', 'adjetivo'),
  ('guay', 'guay, chulo, mola', 'bacán, la raja, filete, chori, pulento', 'Muy bueno, estupendo.', 'Valoración y aprobación', 'adjetivo'),
  ('de-puta-madre-vulg', 'de puta madre (vulg.)', 'la raja, la zorra (vulg.)', 'Excelente, en registro malsonante.', 'Valoración y aprobación', 'adjetivo'),
  ('chachi', 'chachi, dabuten, fetén (ant.)', 'cachilupi, pulento (ant.)', 'Excelente, estupendo; voces de generaciones anteriores.', 'Valoración y aprobación', 'adjetivo'),
  ('de-locos', 'de locos, brutal, top', 'terrible bueno, demasiado bueno, slay (juv.)', 'Increíble, impresionante.', 'Valoración y aprobación', 'adjetivo'),
  ('ser-la-leche', 'ser la leche, ser la hostia', 'ser la raja, ser lo máximo', 'Ser buenísimo; según el tono, también ''ser el colmo''.', 'Valoración y aprobación', 'expresión verbal'),
  ('molar-mucho', 'molar mucho', 'estar la raja, gustar caleta', 'Gustar mucho algo.', 'Valoración y aprobación', 'verbo'),
  ('me-renta', 'me renta', 'me conviene, vale la pena', 'Algo merece la pena o compensa.', 'Valoración y aprobación', 'verbo'),
  ('chapo', 'chapó', '¡bien ahí!, ¡la rompiste!', 'Expresión de admiración por algo bien hecho.', 'Muletillas y expresiones', 'interjección'),
  ('ser-un-crack', 'ser un crack, un máquina, un fiera', 'ser seco, ser capo, la lleva', 'Ser muy hábil o destacar en algo.', 'Valoración y aprobación', 'expresión verbal'),
  ('de-lujo', 'de lujo, de diez, de cine', 'de lujo, la raja, impeque', 'Perfecto, excelente.', 'Valoración y aprobación', 'adjetivo'),
  ('ni-fu-ni-fa', 'ni fu ni fa, regulín', 'más o menos, ahí no más', 'Mediocre, ni bueno ni malo.', 'Valoración y aprobación', 'adjetivo'),
  ('potable-aceptable', 'potable (aceptable)', 'pasable, ahí no más', 'Aceptable sin más. Ojo: en Chile ''potable'' es ''atractivo''.', 'Falsos amigos', 'adjetivo'),
  ('una-mierda-vulg', 'una mierda (vulg.), una basura', 'una cagada (vulg.), último, una porquería', 'De pésima calidad.', 'Valoración y aprobación', 'sustantivo'),
  ('fatal', 'fatal, de pena', 'como el forro, como las weas (vulg.), pésimo', 'Muy mal.', 'Valoración y aprobación', 'adjetivo'),
  ('chulo-bonito', 'chulo (bonito)', 'lindo, regio, bacán', 'Bonito, vistoso. Ojo: en Chile ''chulo'' es ''ordinario, de mal gusto''.', 'Falsos amigos', 'adjetivo'),
  ('mono', 'mono, cuqui', 'tierno, lindo, cuchi', 'Bonito y tierno.', 'Valoración y aprobación', 'adjetivo'),
  ('guarro', 'guarro, cerdo', 'cochino, chancho', 'Sucio.', 'Valoración y aprobación', 'adjetivo'),
  ('guarrada', 'guarrada, cochinada', 'chanchada', 'Acción sucia; en Chile también ''traición o jugarreta''.', 'Valoración y aprobación', 'sustantivo'),
  ('vale', 'vale', 'ya, ya po, dale', 'Expresión de acuerdo.', 'Muletillas y expresiones', 'muletilla'),
  ('sabes', '¿sabes?, ¿me entiendes?', '¿cachai?', 'Muletilla para comprobar que el otro entiende.', 'Muletillas y expresiones', 'muletilla'),
  ('pillar', 'pillar, coscarse, enterarse', 'cachar', 'Entender o darse cuenta de algo.', 'Muletillas y expresiones', 'verbo'),
  ('pillar-sorprender', 'pillar (sorprender)', 'pillar, cachar', 'Descubrir a alguien haciendo algo.', 'Muletillas y expresiones', 'verbo'),
  ('pues-muletilla', 'pues (muletilla)', 'po', 'Muletilla enfática al final de frase: ''sí po'', ''ya po''.', 'Muletillas y expresiones', 'muletilla'),
  ('no', '¿no?, ¿verdad?', '¿o no?, ¿onofre?', 'Coletilla para pedir confirmación.', 'Muletillas y expresiones', 'muletilla'),
  ('o-sea', 'o sea, en plan, tipo', 'o sea, como que, onda', 'Muletillas para introducir explicaciones o ejemplos.', 'Muletillas y expresiones', 'muletilla'),
  ('que-pasa', '¿qué pasa?, ¿qué tal?, ¿qué hay?', '¿qué onda?, ¿quiubo?, ¿cómo estai?', 'Saludo informal.', 'Muletillas y expresiones', 'muletilla'),
  ('buenas', '¡buenas!, ¡hola!', '¡wena!, ¡hola!', 'Saludo informal breve.', 'Muletillas y expresiones', 'muletilla'),
  ('hasta-luego', 'hasta luego, nos vemos, chao', 'chao, nos vemos, nos vidrios', 'Despedida informal.', 'Muletillas y expresiones', 'muletilla'),
  ('de-que-va-esto', '¿de qué va esto?, ¿qué movida es esta?', '¿qué volá?, ¿cuál es la onda?', 'Pregunta por lo que está pasando o el ambiente.', 'Muletillas y expresiones', 'muletilla'),
  ('me-da-que', 'me da que, me huele que', 'me tinca', 'Tener la corazonada o la impresión de algo.', 'Muletillas y expresiones', 'verbo'),
  ('te-apetece', '¿te apetece?, ¿te hace?', '¿te tinca?', 'Proponer un plan preguntando si el otro tiene ganas.', 'Muletillas y expresiones', 'verbo'),
  ('ni-de-cona', 'ni de coña, ni de broma, ni hablar', 'ni cagando (vulg.), nica, ni a palos', 'Negación rotunda.', 'Muletillas y expresiones', 'muletilla'),
  ('por-supuesto', 'por supuesto, claro, obvio', 'obvio, de más, claro po', 'Afirmación rotunda.', 'Muletillas y expresiones', 'muletilla'),
  ('me-la-suda', 'me la suda, me la pela (vulg.), me importa un pimiento', 'no estoy ni ahí, filo, me importa un pucho', 'No importar nada.', 'Emociones y estados de ánimo', 'expresión verbal'),
  ('pasar-de-algo-o-alguien', 'pasar de algo o alguien', 'no estar ni ahí con, no pescar, dar filo', 'Ignorar o desinteresarse de algo o alguien.', 'Emociones y estados de ánimo', 'verbo'),
  ('hacer-caso', 'hacer caso', 'pescar, inflar, dar pelota', 'Prestar atención a alguien.', 'Muletillas y expresiones', 'expresión verbal'),
  ('flipar', 'flipar, alucinar, quedarse loco', 'quedar loco, quedar plop, marcar ocupado', 'Sorprenderse mucho.', 'Emociones y estados de ánimo', 'verbo'),
  ('que-fuerte', '¡qué fuerte!, ¡tela!', '¡qué heavy!, ¡qué cuático!, ¡terrible!', 'Exclamación ante algo sorprendente o escandaloso.', 'Muletillas y expresiones', 'interjección'),
  ('ostras', '¡ostras!, ¡jo!, ¡jolín!, ¡madre mía!', '¡chuta!, ¡pucha!, ¡chuleta!', 'Interjección suave de sorpresa, fastidio o susto.', 'Muletillas y expresiones', 'interjección'),
  ('joder', '¡joder!, ¡hostia!, ¡me cago en la leche! (vulg.)', '¡chucha!, ¡puta!, ¡por la cresta!', 'Interjección fuerte de enfado, dolor o sorpresa.', 'Muletillas y expresiones', 'interjección'),
  ('anda-ya', '¡anda ya!, ¡venga ya!, ¡no me digas!', '¡a dónde la viste!, ¡mentira!, ¡no te creo!', 'Expresión de incredulidad.', 'Muletillas y expresiones', 'interjección'),
  ('vete-a-freir-esparragos', '¡vete a freír espárragos!, ¡a tomar viento!', '¡anda a bañarte!, ¡ándate a la cresta!', 'Mandar a alguien a paseo.', 'Muletillas y expresiones', 'interjección'),
  ('no-me-fastidies', '¡no me fastidies!, ¡no me jodas! (vulg.)', '¡no me lesees!, ¡no me webees! (vulg.)', 'Pedir que no molesten o expresar incredulidad molesta.', 'Muletillas y expresiones', 'interjección'),
  ('que-rollo', '¡qué rollo!, ¡qué coñazo! (vulg.)', '¡qué lata!, ¡qué fome!', 'Expresión de aburrimiento o fastidio.', 'Emociones y estados de ánimo', 'interjección'),
  ('aburrido', 'aburrido, un muermo, un tostón', 'fome, latero', 'Aburrido, sin gracia.', 'Valoración y aprobación', 'adjetivo'),
  ('plasta', 'plasta, pesado, cansino, brasas', 'latero, denso, cargante', 'Persona pesada o aburrida.', 'Personas y tipos sociales', 'adjetivo'),
  ('dar-la-lata', 'dar la lata, dar la turra, dar la brasa, dar la chapa', 'catetear, dar la lata, joder (vulg.)', 'Molestar insistiendo o hablando sin parar.', 'Emociones y estados de ánimo', 'expresión verbal'),
  ('pesado', 'pesado, insistente', 'catete', 'Persona que insiste demasiado.', 'Personas y tipos sociales', 'adjetivo'),
  ('que-pereza', '¡qué pereza!, ¡qué palo!', '¡qué paja!, ¡qué lata!', 'Expresión de falta de ganas.', 'Emociones y estados de ánimo', 'interjección'),
  ('vago', 'vago, gandul', 'flojo', 'Persona perezosa.', 'Personas y tipos sociales', 'adjetivo'),
  ('vaguear', 'vaguear, tocarse las narices, no dar palo al agua', 'flojear, no mover un dedo', 'No hacer nada, holgazanear.', 'Trabajo y estudio', 'verbo'),
  ('hecho-polvo-1', 'hecho polvo, reventado, molido', 'raja, muerto, chato', 'Muy cansado.', 'Cuerpo y salud', 'adjetivo'),
  ('estar-harto', 'estar harto, hasta las narices, hasta el moño', 'estar chato, hasta la tusa, aburrido', 'Estar harto de algo o alguien.', 'Emociones y estados de ánimo', 'expresión verbal'),
  ('estar-de-bajon', 'estar de bajón, estar chof', 'estar bajoneado, achacado, con el bajón', 'Triste, desanimado.', 'Emociones y estados de ánimo', 'expresión verbal'),
  ('venirse-abajo', 'venirse abajo', 'achacarse, bajonearse', 'Entristecerse o desanimarse.', 'Emociones y estados de ánimo', 'verbo'),
  ('comerse-el-coco', 'comerse el coco, rayarse', 'enrollarse, perseguirse, darse vueltas', 'Darle vueltas obsesivamente a algo negativo.', 'Emociones y estados de ánimo', 'verbo'),
  ('agobiarse', 'agobiarse, estar agobiado', 'estresarse, estar colapsado', 'Sentirse sobrepasado.', 'Emociones y estados de ánimo', 'verbo'),
  ('cabrearse', 'cabrearse, mosquearse', 'chorearse, picarse, emputecerse (vulg.)', 'Enfadarse.', 'Emociones y estados de ánimo', 'verbo'),
  ('cabreado', 'cabreado, mosqueado, de mala leche', 'choreado, picado, enojado', 'Enfadado, de mal humor.', 'Emociones y estados de ánimo', 'adjetivo'),
  ('enfurrunado', 'enfurruñado, mosca', 'amurrado', 'Enojado y callado, con cara larga.', 'Emociones y estados de ánimo', 'adjetivo'),
  ('tener-mala-leche', 'tener mala leche', 'tener mal genio', 'Tener mal carácter. Ojo: en Chile ''mala leche'' es ''mala suerte'' o ''mala intención''.', 'Falsos amigos', 'expresión verbal'),
  ('echar-la-bronca', 'echar la bronca, poner a caldo', 'echar la foca, retar', 'Regañar a alguien con dureza.', 'Emociones y estados de ánimo', 'expresión verbal'),
  ('echar-en-cara', 'echar en cara', 'sacar en cara', 'Reprochar a alguien un favor o un error.', 'Emociones y estados de ánimo', 'expresión verbal'),
  ('tirar-una-pulla', 'tirar una pulla, lanzar una indirecta', 'tirar un palo', 'Hacer un comentario indirecto con mala intención. Ojo: en España ''dar palo'' es ''dar pereza o vergüenza''.', 'Falsos amigos', 'expresión verbal'),
  ('dar-envidia', 'dar envidia, picar', 'sacar pica, dar pica', 'Provocar envidia o celos.', 'Emociones y estados de ánimo', 'expresión verbal'),
  ('que-corte', '¡qué corte!, ¡qué vergüenza!', '¡qué plancha!', 'Expresión de vergüenza propia.', 'Emociones y estados de ánimo', 'interjección'),
  ('verguenza-ajena', 'vergüenza ajena, cringe, lache (juv.)', 'plancha ajena, cringe (juv.)', 'Vergüenza que se siente por lo que hace otro.', 'Emociones y estados de ánimo', 'sustantivo'),
  ('hacer-el-ridiculo', 'hacer el ridículo, hacer el payaso', 'pintar el mono, hacer el loco', 'Comportarse de forma ridícula delante de otros.', 'Emociones y estados de ánimo', 'expresión verbal'),
  ('quedar-fatal', 'quedar fatal, quedar como el culo (vulg.)', 'quedar como chaleco de mono', 'Salir muy mal parado de una situación.', 'Emociones y estados de ánimo', 'expresión verbal'),
  ('canguelo', 'canguelo, acojone (vulg.)', 'julepe, cuco, susto', 'Miedo.', 'Emociones y estados de ánimo', 'sustantivo'),
  ('acojonar', 'acojonar, meter miedo', 'meter cuco, asustar', 'Asustar a alguien.', 'Emociones y estados de ánimo', 'verbo'),
  ('cagueta', 'cagueta, gallina', 'arrugón, cagado', 'Cobarde.', 'Personas y tipos sociales', 'sustantivo'),
  ('rajarse', 'rajarse, echarse atrás', 'arrugar, achaplinarse', 'Arrepentirse de hacer algo por miedo.', 'Emociones y estados de ánimo', 'verbo'),
  ('apechugar', 'apechugar, aguantar carros y carretas', 'aperrar, bancarse, apechugar', 'Aguantar una situación difícil y seguir adelante.', 'Emociones y estados de ánimo', 'verbo'),
  ('acompanar', 'acompañar, cubrir a un colega', 'apañar', 'Acompañar o apoyar a alguien. Ojo: en España ''apañarse'' es ''arreglárselas''.', 'Falsos amigos', 'verbo'),
  ('buen-rollo', 'buen rollo, mal rollo', 'buena onda, mala onda', 'Buen o mal ambiente o energía entre personas.', 'Amistad y trato social', 'sustantivo'),
  ('majo', 'majo, enrollado, legal', 'buena onda, buena gente, buena leche', 'Persona simpática, agradable y de fiar.', 'Personas y tipos sociales', 'adjetivo'),
  ('dar-mal-rollo', 'dar mal rollo, dar mala espina', 'dar mala espina, dar cosa, dar mala onda', 'Provocar desconfianza o inquietud.', 'Emociones y estados de ánimo', 'expresión verbal'),
  ('tranqui', 'tranqui, de chill, relax', 'piola, tranqui, relajado', 'Tranquilo, sin estrés.', 'Emociones y estados de ánimo', 'adjetivo'),
  ('de-tapadillo', 'de tapadillo, de extranjis', 'piola, pa'' callado, al callado', 'En secreto, sin que se note.', 'Muletillas y expresiones', 'expresión adverbial'),
  ('pasar-desapercibido', 'pasar desapercibido', 'pasar piola', 'Hacer algo sin llamar la atención.', 'Muletillas y expresiones', 'verbo'),
  ('estar-en-el-ajo', 'estar en el ajo', 'estar metido en la cuestión, estar en la volada', 'Estar enterado o implicado en un asunto reservado.', 'Muletillas y expresiones', 'expresión verbal'),
  ('al-loro', '¡al loro!', '¡ojo!, al aguaite', 'Atención, estar alerta.', 'Muletillas y expresiones', 'interjección'),
  ('tener-potra', 'tener potra, tener chorra, tener flor', 'tener cueva, tener raja (vulg.)', 'Tener suerte.', 'Suerte', 'expresión verbal'),
  ('potroso', 'potroso, suertudo', 'cuevudo, rajudo (vulg.)', 'Persona con mucha suerte.', 'Suerte', 'adjetivo'),
  ('de-chiripa', 'de chiripa, de potra', 'de pura cueva, de chiripa', 'Por pura suerte.', 'Suerte', 'expresión adverbial'),
  ('gafe', 'gafe, cenizo', 'salado, pájaro de mal agüero', 'Persona con mala suerte o que la trae. Ojo: en España ''salado'' es ''gracioso''.', 'Falsos amigos', 'sustantivo'),
  ('que-mala-pata', '¡qué mala pata!', '¡qué mala cueva!, ¡qué penca!', 'Expresión de mala suerte.', 'Suerte', 'interjección'),
  ('que-pena', '¡qué pena!, ¡qué lástima!', '¡qué penca!, ¡qué lata!', 'Expresión de lástima.', 'Emociones y estados de ánimo', 'interjección'),
  ('no-dar-pie-con-bola', 'no dar pie con bola', 'no achuntarle a ni una, no pegar ni una', 'Equivocarse una y otra vez.', 'Suerte', 'expresión verbal'),
  ('dar-en-el-clavo', 'dar en el clavo', 'achuntar, dar en el clavo', 'Acertar.', 'Suerte', 'expresión verbal'),
  ('tomar-el-pelo', 'tomar el pelo, vacilar, quedarse con alguien', 'agarrar pa''l leseo, agarrar pa''l hueveo (vulg.), lesear', 'Burlarse de alguien con bromas.', 'Chismes, bromas y mentiras', 'expresión verbal'),
  ('estar-de-cona', 'estar de coña, estar de cachondeo', 'tirar la talla, chacotear, estar en la talla', 'Bromear.', 'Chismes, bromas y mentiras', 'expresión verbal'),
  ('cona', 'coña, broma, gracia', 'talla, chacota', 'Broma o chiste.', 'Chismes, bromas y mentiras', 'sustantivo'),
  ('pegar-la-hebra', 'pegar la hebra, estar de cháchara', 'echar la talla, conversar', 'Pasar el rato charlando y bromeando.', 'Chismes, bromas y mentiras', 'expresión verbal'),
  ('cachondo', 'cachondo, salado, cachondo mental', 'chistoso, tallero, choro (entretenido)', 'Persona graciosa.', 'Personas y tipos sociales', 'adjetivo'),
  ('es-cona', '¿es coña?', '¿es broma?, ¿es talla?', 'Pregunta para saber si algo va en serio.', 'Chismes, bromas y mentiras', 'muletilla'),
  ('en-serio', 'en serio, palabra', 'la firme, la dura, la pulenta, en buena', 'De verdad, sin bromas.', 'Muletillas y expresiones', 'expresión adverbial'),
  ('chorrada', 'chorrada, tontería, gilipollez (vulg.)', 'lesera, tontera, weá (vulg.)', 'Tontería, cosa sin importancia.', 'Chismes, bromas y mentiras', 'sustantivo'),
  ('decir-chorradas', 'decir chorradas', 'hablar cabezas de pescado, decir leseras, dar jugo', 'Decir tonterías o incoherencias.', 'Chismes, bromas y mentiras', 'expresión verbal'),
  ('hacer-el-tonto', 'hacer el tonto, hacer el ganso', 'lesear, webiar (vulg.)', 'Comportarse de forma tonta o perder el tiempo.', 'Chismes, bromas y mentiras', 'verbo'),
  ('hacerse-el-longui', 'hacerse el longui, hacerse el sueco', 'hacerse el weón (vulg.), hacerse el leso', 'Fingir no enterarse.', 'Chismes, bromas y mentiras', 'expresión verbal'),
  ('bola', 'bola, trola, bulo', 'chiva, carril, cuento, grupo', 'Mentira o excusa.', 'Chismes, bromas y mentiras', 'sustantivo'),
  ('bolero', 'bolero, trolero, cuentista', 'chivero, carrilero, cuentero, grupiento', 'Mentiroso.', 'Personas y tipos sociales', 'sustantivo'),
  ('camelar', 'camelar, engatusar', 'engrupir', 'Convencer o seducir a alguien con engaños o palabrería.', 'Chismes, bromas y mentiras', 'verbo'),
  ('hablar-por-los-codos', 'hablar por los codos', 'hablar hasta por los codos, ser lora', 'Hablar muchísimo.', 'Personas y tipos sociales', 'expresión verbal'),
  ('en-resumidas-cuentas', 'en resumidas cuentas', 'hacerla corta', 'Resumir lo que se va a decir.', 'Muletillas y expresiones', 'expresión adverbial'),
  ('ponerse-trascendental', 'ponerse trascendental', 'irse en la profunda', 'Ponerse a filosofar sobre la vida.', 'Chismes, bromas y mentiras', 'verbo'),
  ('buscarle-tres-pies-al-gato', 'buscarle tres pies al gato', 'buscarle la quinta pata al gato', 'Complicar las cosas buscando problemas donde no los hay.', 'Problemas, líos y errores', 'expresión verbal'),
  ('pasarse-tres-pueblos', 'pasarse tres pueblos, pasarse de castaño oscuro', 'irse al chancho, pasarse', 'Exagerar, excederse.', 'Chismes, bromas y mentiras', 'verbo'),
  ('echarle-teatro', 'echarle teatro, exagerar', 'ponerle color, darse color', 'Exagerar o dramatizar algo.', 'Chismes, bromas y mentiras', 'verbo'),
  ('echarle-ganas', 'echarle ganas, darlo todo', 'ponerle pino, ponerle empeño', 'Hacer algo con mucho entusiasmo y esfuerzo.', 'Cantidad, tiempo e intensidad', 'expresión verbal'),
  ('estar-a-tope', 'estar a tope, ir a saco', 'a full, a concho', 'Con máxima intensidad o hasta el final.', 'Cantidad, tiempo e intensidad', 'expresión adverbial'),
  ('a-la-bartola', 'a la bartola, de cualquier manera', 'al lote, a la que te criaste', 'Sin cuidado, de forma desordenada.', 'Cantidad, tiempo e intensidad', 'expresión adverbial'),
  ('a-ojo-de-buen-cubero', 'a ojo de buen cubero', 'al ojo, al cálculo', 'De forma aproximada, sin medir.', 'Cantidad, tiempo e intensidad', 'expresión adverbial'),
  ('por-si-las-moscas', 'por si las moscas', 'por si las moscas', 'Por si acaso.', 'Muletillas y expresiones', 'expresión adverbial'),
  ('dejar-plantado', 'dejar plantado, dar plantón, dejar tirado', 'dejar plantado, dejar botado', 'No acudir a una cita o abandonar a alguien.', 'Amor y relaciones', 'expresión verbal'),
  ('hacer-una-bomba-de-humo', 'hacer una bomba de humo, irse a la francesa', 'desaparecer piola', 'Irse de una fiesta sin despedirse.', 'Fiesta, alcohol y drogas', 'expresión verbal'),
  ('pirarse', 'pirarse, abrirse, largarse', 'virarse, echarse el pollo, cortarla', 'Irse de un lugar.', 'Muletillas y expresiones', 'verbo'),
  ('salir-pitando', 'salir pitando, salir por patas', 'apretar cachete, salir cascando, salir rajado', 'Irse corriendo o huir.', 'Muletillas y expresiones', 'expresión verbal'),
  ('aligera', '¡aligera!, ¡date prisa!', '¡apura!, ¡chicotea los caracoles!, ¡ya po!', 'Pedir que alguien se dé prisa.', 'Muletillas y expresiones', 'interjección'),
  ('a-toda-leche', 'a toda leche, a toda pastilla, a toda hostia (vulg.)', 'a toda raja, a todo chancho, rajado', 'A máxima velocidad.', 'Cantidad, tiempo e intensidad', 'expresión adverbial'),
  ('ahora-mismo', 'ahora mismo, en un pispás, en un plis', 'al tiro, altiro, al toque', 'Inmediatamente.', 'Cantidad, tiempo e intensidad', 'expresión adverbial'),
  ('luego', 'luego, ahora (más tarde)', 'al rato, de ahí', 'Más tarde, después.', 'Cantidad, tiempo e intensidad', 'expresión adverbial'),
  ('del-ano-de-la-pera', 'del año de la pera, del año catapum', 'del año de la cocoa, del año del loly', 'De hace muchísimo tiempo.', 'Cantidad, tiempo e intensidad', 'expresión adverbial'),
  ('en-el-quinto-pino', 'en el quinto pino, donde Cristo perdió el mechero', 'donde el diablo perdió el poncho, en Chuchunco', 'Muy lejos.', 'Cantidad, tiempo e intensidad', 'expresión adverbial'),
  ('mas-perdido-que-un-pulpo-en-un-garaje', 'más perdido que un pulpo en un garaje', 'más perdido que el teniente Bello', 'Totalmente desorientado o fuera de lugar.', 'Emociones y estados de ánimo', 'adjetivo'),
  ('mas-solo-que-la-una', 'más solo que la una', 'más solo que perro en la micro, más solo que un dedo', 'Completamente solo.', 'Emociones y estados de ánimo', 'adjetivo'),
  ('mogollon', 'mogollón, la tira, un huevo (vulg.), a cascoporro', 'caleta, ene, harto, un montón', 'Mucho, gran cantidad.', 'Cantidad, tiempo e intensidad', 'expresión adverbial'),
  ('mazo', 'mazo, muy', 'súper, re, demasiado, terrible', 'Intensificador: muy, mucho (''mazo bueno'', ''terrible bueno'').', 'Cantidad, tiempo e intensidad', 'expresión adverbial'),
  ('un-pelin', 'un pelín, una pizca', 'un pichintún, un poquito no más, un cachito', 'Muy poca cantidad.', 'Cantidad, tiempo e intensidad', 'expresión adverbial'),
  ('a-punta-pala', 'a punta pala, a porrillo', 'a patadas, por montones', 'En gran abundancia.', 'Cantidad, tiempo e intensidad', 'expresión adverbial'),
  ('petado', 'petado, a reventar', 'lleno, repleto, a full', 'Lleno de gente.', 'Cantidad, tiempo e intensidad', 'adjetivo'),
  ('no-pegar-ojo', 'no pegar ojo', 'no pegar pestaña', 'No poder dormir.', 'Cuerpo y salud', 'expresión verbal'),
  ('sobar', 'sobar, planchar la oreja', 'hacer tuto, apoliyar', 'Dormir.', 'Cuerpo y salud', 'verbo'),
  ('tener-sueno', 'tener sueño', 'tener tuto', 'Tener ganas de dormir.', 'Cuerpo y salud', 'expresión verbal'),
  ('irse-al-sobre', 'irse al sobre', 'irse al sobre', 'Irse a dormir.', 'Cuerpo y salud', 'expresión verbal'),
  ('echar-una-cabezadita', 'echar una cabezadita', 'echarse una pestañita', 'Dormir una siesta corta.', 'Cuerpo y salud', 'expresión verbal'),
  ('arreglarse', 'arreglarse, chapa y pintura', 'darse una manito de gato', 'Arreglarse o maquillarse rápidamente.', 'Cuerpo y salud', 'verbo'),
  ('pinta', 'pinta, aspecto', 'facha, pinta', 'Apariencia de una persona o cosa.', 'Cuerpo y salud', 'sustantivo'),
  ('en-pelotas', 'en pelotas, en bolas, en cueros', 'pilucho, calato, en pelota', 'Desnudo.', 'Cuerpo y salud', 'adjetivo'),
  ('tripa', 'tripa, panza, barriga', 'guata, buche', 'Barriga, estómago.', 'Cuerpo y salud', 'sustantivo'),
  ('gordo', 'gordo, gordinflón', 'guatón, guatona', 'Persona gorda o con barriga; en Chile también apelativo cariñoso.', 'Cuerpo y salud', 'adjetivo'),
  ('cachas', 'cachas, mazado', 'marcado, musculoso', 'Persona musculosa.', 'Cuerpo y salud', 'adjetivo'),
  ('calvo', 'calvo, calvorota', 'pelado', 'Persona calva o con el pelo muy corto.', 'Cuerpo y salud', 'adjetivo'),
  ('grenas', 'greñas, despeinado', 'chascón, chascona, chasca', 'Pelo revuelto o muy desordenado.', 'Cuerpo y salud', 'adjetivo'),
  ('culo', 'culo, trasero, pandero', 'poto, queque', 'Nalgas, trasero.', 'Cuerpo y salud', 'sustantivo'),
  ('coco', 'coco, tarro, chola', 'mate, cabeza', 'Cabeza.', 'Cuerpo y salud', 'sustantivo'),
  ('pinreles', 'pinreles', 'patas', 'Pies.', 'Cuerpo y salud', 'sustantivo'),
  ('jeta', 'jeta, careto', 'jeta, cara', 'Cara de una persona, dicho de forma coloquial.', 'Cuerpo y salud', 'sustantivo'),
  ('mear', 'mear, hacer pis', 'hacer pichí', 'Orinar.', 'Cuerpo y salud', 'verbo'),
  ('potar', 'potar, echar la pota', 'guitrear, echar la buena', 'Vomitar, sobre todo por exceso de alcohol.', 'Cuerpo y salud', 'verbo'),
  ('estar-pachucho', 'estar pachucho, estar fatal', 'estar pa''l gato, andar mal', 'Encontrarse mal o enfermo.', 'Cuerpo y salud', 'expresión verbal'),
  ('palmarla', 'palmarla, estirar la pata, irse al otro barrio', 'estirar la pata, parar las chalas', 'Morir.', 'Cuerpo y salud', 'expresión verbal'),
  ('darse-una-leche', 'darse una leche, pegarse una hostia (vulg.)', 'sacarse la cresta, sacarse la mugre', 'Caerse o darse un golpe fuerte.', 'Golpes y peleas', 'expresión verbal'),
  ('dar-una-paliza', 'dar una paliza, dar de hostias (vulg.)', 'sacar la cresta, sacar la mugre, pegar una pateadura', 'Pegar a alguien.', 'Golpes y peleas', 'expresión verbal'),
  ('guantazo', 'guantazo, tortazo, bofetón', 'charchazo, cachetada', 'Bofetada.', 'Golpes y peleas', 'sustantivo'),
  ('punetazo', 'puñetazo, piña', 'combo', 'Puñetazo.', 'Golpes y peleas', 'sustantivo'),
  ('colleja', 'colleja, capón', 'coscacho', 'Golpe con la mano en la nuca o la cabeza.', 'Golpes y peleas', 'sustantivo'),
  ('bronca', 'bronca, pelea, movida', 'rosca, boche, pelea', 'Pelea o discusión fuerte.', 'Golpes y peleas', 'sustantivo'),
  ('fiesta', 'fiesta, juerga, farra, sarao', 'carrete, jarana, tono', 'Fiesta.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('salir-de-fiesta', 'salir de fiesta, ir de marcha', 'carretear', 'Salir a divertirse por la noche.', 'Fiesta, alcohol y drogas', 'verbo'),
  ('fiestero', 'fiestero, juerguista', 'carretero', 'Persona a la que le gusta mucho salir de fiesta.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('pasarlo-bomba', 'pasarlo bomba, pasarlo pipa', 'pasarlo chancho, pasarlo la raja, pasarlo bomba', 'Divertirse mucho.', 'Fiesta, alcohol y drogas', 'expresión verbal'),
  ('cortar-el-rollo', 'cortar el rollo', 'cortar la onda, cortar el carrete', 'Interrumpir un buen momento o un ambiente agradable.', 'Fiesta, alcohol y drogas', 'expresión verbal'),
  ('garito', 'garito, antro', 'boliche, antro', 'Bar o local nocturno, a menudo de poca categoría.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('hacer-la-previa', 'hacer la previa, precopeo', 'la previa', 'Reunión para beber antes de salir de fiesta.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('botellon', 'botellón', null, 'Reunión de jóvenes al aire libre para beber alcohol comprado en tiendas. En Chile no hay término específico.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('verbena', 'verbena, feria, fiestas del pueblo', 'fonda, ramada', 'Fiesta popular con baile, comida y bebida; en Chile, la de Fiestas Patrias.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('priva', 'priva, alcohol', 'copete', 'Bebida alcohólica.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('privar', 'privar, pimplar, beber', 'chupar, tomar', 'Beber alcohol.', 'Fiesta, alcohol y drogas', 'verbo'),
  ('birra', 'birra', 'chela', 'Cerveza.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('cana', 'caña', 'schop', 'Cerveza de barril servida en vaso.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('litrona', 'litrona', 'un litro', 'Botella de cerveza de un litro.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('cubata', 'cubata', 'piscola, combinado', 'Combinado de licor con refresco; en Chile el típico es pisco con bebida cola.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('calimocho', 'calimocho', 'jote', 'Vino tinto mezclado con refresco de cola.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('chupito', 'chupito', 'corto, cortito, shot', 'Trago pequeño de licor que se bebe de golpe.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('tinto-de-verano', 'tinto de verano', null, 'Vino tinto con gaseosa, bebida veraniega española.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('terremoto', null, 'terremoto', 'Cóctel chileno de pipeño con helado de piña.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('vino-de-tetrabrik', 'vino de tetrabrik', 'vino en caja', 'Vino barato envasado en cartón.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('ir-de-canas', 'ir de cañas', 'salir a tomarse unas chelas', 'Salir a beber cerveza con amigos.', 'Fiesta, alcohol y drogas', 'expresión verbal'),
  ('coger-el-puntillo', 'coger el puntillo, estar piripi', 'estar entonado, estar arriba de la pelota', 'Estar algo bebido y alegre, sin llegar a la borrachera.', 'Fiesta, alcohol y drogas', 'expresión verbal'),
  ('pedo', 'pedo, ciego, mamado, pillar una cogorza', 'curado, cocido, raja de curado', 'Borracho, o emborracharse mucho.', 'Fiesta, alcohol y drogas', 'adjetivo'),
  ('emborracharse', 'emborracharse, pillarse un pedo', 'curarse', 'Emborracharse.', 'Fiesta, alcohol y drogas', 'verbo'),
  ('resaca', 'resaca, resacón', 'caña, hachazo', 'Malestar del día siguiente por beber demasiado.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('porro', 'porro, peta', 'pito, caño', 'Cigarrillo de marihuana.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('colocado', 'colocado, fumado', 'volado', 'Bajo los efectos de alguna droga.', 'Fiesta, alcohol y drogas', 'adjetivo'),
  ('pitillo', 'pitillo, piti, cigarro', 'pucho', 'Cigarrillo.', 'Fiesta, alcohol y drogas', 'sustantivo'),
  ('tapa', 'tapa, pincho', 'picoteo', 'Pequeña porción de comida para acompañar la bebida.', 'Comida y bebida', 'sustantivo'),
  ('ir-de-tapas', 'ir de tapas', null, 'Recorrer bares tomando bebidas y tapas. En Chile no existe la costumbre.', 'Comida y bebida', 'expresión verbal'),
  ('papeo', 'papeo, manduca', 'la comida, el bajón', 'Comida; en Chile ''bajón'' es la comida chatarra a deshoras, tras una fiesta.', 'Comida y bebida', 'sustantivo'),
  ('tener-gusa', 'tener gusa', 'estar cagado de hambre (vulg.), tener un hambre de lobo', 'Tener mucha hambre.', 'Comida y bebida', 'expresión verbal'),
  ('ponerse-morado', 'ponerse morado, darse un atracón', 'darse un atracón, comer como chancho', 'Comer en exceso.', 'Comida y bebida', 'expresión verbal'),
  ('comida-basura', 'comida basura, guarradas', 'comida chatarra', 'Comida poco saludable, rápida y procesada.', 'Comida y bebida', 'sustantivo'),
  ('merienda', 'merienda', 'once', 'Comida de la tarde; en Chile es té con pan y acompañamientos, a menudo sustituye a la cena.', 'Comida y bebida', 'sustantivo'),
  ('bocata', 'bocata', 'sánguche, sanguchito', 'Bocadillo o sándwich.', 'Comida y bebida', 'sustantivo'),
  ('perrito-caliente', 'perrito caliente', 'completo', 'Salchicha en pan; en Chile, con palta, tomate y mayonesa.', 'Comida y bebida', 'sustantivo'),
  ('palomitas', 'palomitas', 'cabritas', 'Maíz inflado.', 'Comida y bebida', 'sustantivo'),
  ('chuches', 'chuches', 'dulces, golosinas', 'Caramelos y golosinas.', 'Comida y bebida', 'sustantivo'),
  ('aguacate', 'aguacate', 'palta', 'Fruto verde y cremoso usado en ensaladas y sándwiches.', 'Comida y bebida', 'sustantivo'),
  ('fresa', 'fresa', 'frutilla', 'Fruta roja pequeña y dulce.', 'Comida y bebida', 'sustantivo'),
  ('melocoton', 'melocotón', 'durazno', 'Fruta de piel aterciopelada.', 'Comida y bebida', 'sustantivo'),
  ('albaricoque', 'albaricoque', 'damasco', 'Fruta pequeña de color anaranjado.', 'Comida y bebida', 'sustantivo'),
  ('mazorca', 'mazorca, maíz', 'choclo', 'Mazorca o grano de maíz tierno.', 'Comida y bebida', 'sustantivo'),
  ('judias', 'judías', 'porotos', 'Legumbre seca.', 'Comida y bebida', 'sustantivo'),
  ('judias-verdes', 'judías verdes', 'porotos verdes', 'Vaina verde comestible.', 'Comida y bebida', 'sustantivo'),
  ('guisantes', 'guisantes', 'arvejas', 'Legumbre pequeña y redonda verde.', 'Comida y bebida', 'sustantivo'),
  ('calabaza', 'calabaza', 'zapallo', 'Hortaliza grande de pulpa naranja.', 'Comida y bebida', 'sustantivo'),
  ('calabacin', 'calabacín', 'zapallo italiano', 'Hortaliza alargada verde.', 'Comida y bebida', 'sustantivo'),
  ('remolacha', 'remolacha', 'betarraga', 'Raíz roja comestible.', 'Comida y bebida', 'sustantivo'),
  ('guindilla', 'guindilla', 'ají', 'Pimiento picante.', 'Comida y bebida', 'sustantivo'),
  ('marraqueta', null, 'marraqueta, pan batido', 'Pan crujiente típico chileno que se parte en cuatro.', 'Comida y bebida', 'sustantivo'),
  ('sopaipilla', null, 'sopaipilla', 'Masa frita de zapallo, comida callejera chilena.', 'Comida y bebida', 'sustantivo'),
  ('coche', 'coche, buga', 'auto, nave', 'Automóvil.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('cafetera', 'cafetera, tartana', 'carcacha', 'Coche viejo y en mal estado.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('autobus', 'autobús, bus', 'micro', 'Autobús urbano.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('taxi', 'taxi, teki, pesetero', 'taxi, colectivo (taxi compartido de ruta fija)', 'Taxi; en Chile el colectivo hace un recorrido fijo con varios pasajeros.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('atasco', 'atasco', 'taco', 'Embotellamiento de tráfico.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('baden', 'badén, guardia tumbado', 'lomo de toro', 'Resalto en la calzada para reducir la velocidad.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('gasolinera', 'gasolinera', 'bomba, servicentro', 'Estación de servicio.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('gasolina', 'gasolina', 'bencina', 'Combustible para coches.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('multa', 'multa', 'parte', 'Sanción de tráfico.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('aparcar', 'aparcar', 'estacionar', 'Dejar el vehículo detenido en un lugar.', 'Transporte y objetos cotidianos', 'verbo'),
  ('bici', 'bici', 'bici, cleta', 'Bicicleta.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('ir-a-pata', 'ir a pata, en el coche de San Fernando', 'a pata, a pie', 'Ir caminando.', 'Transporte y objetos cotidianos', 'expresión adverbial'),
  ('colarse', 'colarse', 'colarse', 'Entrar sin pagar o saltarse la fila.', 'Transporte y objetos cotidianos', 'verbo'),
  ('dni', 'DNI', 'carnet', 'Documento de identidad.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('movil', 'móvil', 'celu, celular', 'Teléfono móvil.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('ordenador', 'ordenador, el ordena', 'compu, computador', 'Computadora.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('boli', 'boli, bolígrafo', 'lápiz pasta', 'Bolígrafo.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('rotulador', 'rotulador', 'plumón', 'Marcador de tinta.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('tirita', 'tirita', 'parche curita', 'Apósito adhesivo para heridas pequeñas.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('celo', 'celo', 'scotch', 'Cinta adhesiva transparente.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('pajita', 'pajita', 'bombilla', 'Tubo para sorber bebidas.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('bombilla', 'bombilla', 'ampolleta', 'Lámpara eléctrica.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('grifo', 'grifo', 'llave', 'Llave por donde sale el agua.', 'Transporte y objetos cotidianos', 'sustantivo'),
  ('fontanero', 'fontanero', 'gásfiter', 'Persona que arregla tuberías e instalaciones de agua.', 'Trabajo y estudio', 'sustantivo'),
  ('calentador', 'calentador', 'calefont', 'Aparato que calienta el agua de la casa.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('jersey', 'jersey', 'chaleco', 'Prenda de punto de manga larga.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('chupa', 'chupa, cazadora', 'chaqueta, parka, casaca', 'Prenda de abrigo corta.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('chandal', 'chándal', 'buzo', 'Ropa deportiva de pantalón y chaqueta.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('banador', 'bañador', 'traje de baño', 'Prenda para bañarse.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('bragas', 'bragas', 'calzones', 'Ropa interior femenina.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('gayumbos', 'gayumbos, calzoncillos', 'calzoncillos', 'Ropa interior masculina.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('chanclas', 'chanclas', 'chalas, ojotas', 'Sandalias abiertas y planas.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('botas-de-montana', 'botas de montaña', 'bototos', 'Calzado grueso y resistente con caña.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('pendientes', 'pendientes', 'aros', 'Adornos para las orejas.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('gafas', 'gafas', 'lentes', 'Anteojos.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('piso', 'piso', 'departamento, depa', 'Vivienda dentro de un edificio.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('habitacion', 'habitación, cuarto', 'pieza', 'Dormitorio.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('keli', 'keli, queli, choza', 'la casa, la ruca', 'Casa, hogar.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('piltra', 'piltra', 'catre, cama', 'Cama.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('tirar-a-la-basura', 'tirar (a la basura)', 'botar', 'Deshacerse de algo.', 'Ropa, vivienda y objetos', 'verbo'),
  ('hucha', 'hucha', 'alcancía, chanchito', 'Recipiente para guardar monedas.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('cubiertos', 'cubiertos', 'servicios', 'Cuchillo, tenedor y cuchara.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('tobogan', 'tobogán', 'resbalín', 'Juego infantil para deslizarse.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('cometa', 'cometa', 'volantín', 'Juguete de papel que vuela con el viento.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('chucho', 'chucho', 'quiltro', 'Perro sin raza definida. Ojo: en Chile ''chucho'' es una forma antigua de llamar a la cárcel.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('chuleta', 'chuleta', 'torpedo', 'Papel escondido para copiar en un examen.', 'Trabajo y estudio', 'sustantivo'),
  ('empollar', 'empollar, hincar los codos', 'matearse', 'Estudiar mucho.', 'Trabajo y estudio', 'verbo'),
  ('suspender', 'suspender, catear', 'echarse un ramo, ser rajado', 'Reprobar un examen o asignatura.', 'Trabajo y estudio', 'verbo'),
  ('asignatura', 'asignatura', 'ramo', 'Materia de estudio.', 'Trabajo y estudio', 'sustantivo'),
  ('hacer-pellas', 'hacer pellas, hacer novillos', 'hacer la cimarra', 'Faltar a clase sin permiso.', 'Trabajo y estudio', 'expresión verbal'),
  ('selectividad', 'selectividad, EBAU', 'PAES (antes PSU)', 'Examen de acceso a la universidad.', 'Trabajo y estudio', 'sustantivo'),
  ('hace-un-frio-que-pela', 'hace un frío que pela, hace rasca', 'está helado, hace un frío que cala los huesos', 'Hace mucho frío.', 'Clima', 'expresión verbal'),
  ('hace-un-calor-que-te-cagas-vulg', 'hace un calor que te cagas (vulg.), achicharrarse', 'hace un calor pa'' morirse, derretirse', 'Hace muchísimo calor.', 'Clima', 'expresión verbal'),
  ('llover-a-cantaros', 'llover a cántaros, caer chuzos de punta', 'llover a cántaros, caer un aguacero', 'Llover con mucha fuerza.', 'Clima', 'expresión verbal'),
  ('chirimiri', 'chirimiri, calabobos', 'garúa, llovizna', 'Lluvia fina y persistente.', 'Clima', 'sustantivo'),
  ('calado-hasta-los-huesos', 'calado hasta los huesos', 'estilando', 'Completamente empapado.', 'Clima', 'adjetivo'),
  ('temporal', null, 'temporal', 'Episodio de lluvia y viento fuertes que dura varios días.', 'Clima', 'sustantivo'),
  ('cancelar', 'cancelar, funar', 'funar', 'Denunciar o boicotear públicamente a alguien en redes; en Chile, también arruinar un plan.', 'Jerga reciente y anglicismos', 'verbo'),
  ('crush', 'crush', 'crush', 'Persona que gusta mucho o amor platónico (anglicismo en ambos países).', 'Jerga reciente y anglicismos', 'sustantivo'),
  ('random', 'random', 'random', 'Algo aleatorio, raro o inesperado (anglicismo juvenil en ambos países).', 'Jerga reciente y anglicismos', 'adjetivo'),
  ('estar-en-mi-prime', 'estar en mi prime', 'estar en mi prime', 'Estar en el mejor momento personal (anglicismo juvenil).', 'Jerga reciente y anglicismos', 'expresión verbal'),
  ('menda', 'menda, el menda lerenda', null, 'Forma castiza de referirse a uno mismo: ''yo''.', 'Muletillas y expresiones', 'pronombre'),
  ('cachai', null, 'cachai', 'Muletilla chilena de ''¿entiendes?'' (ver fila de ''¿sabes?'').', 'Muletillas y expresiones', 'verbo'),
  ('once', null, 'once', 'Comida de la tarde-noche chilena con té y pan; sin equivalente exacto en España.', 'Comida y bebida', 'sustantivo'),
  ('huaso', null, 'huaso', 'Campesino tradicional chileno de la zona central.', 'Personas y tipos sociales', 'sustantivo'),
  ('chanchito', null, 'chanchito', 'Hucha con forma de cerdo, tradicional en Chile.', 'Ropa, vivienda y objetos', 'sustantivo'),
  ('la-hora-del-te', null, 'la hora del té, tomar once', 'Momento social de la tarde para comer pan y beber té.', 'Comida y bebida', 'sustantivo'),
  ('coger-tomar', 'coger (tomar)', 'tomar, agarrar', 'Tomar o asir algo. Ojo: en buena parte de América ''coger'' es vulgar (sexo); en Chile se entiende pero se prefiere ''tomar''.', 'Falsos amigos', 'verbo'),
  ('pico-beso-breve', 'pico (beso breve)', 'besito', 'Beso rápido en los labios. Ojo: en Chile ''pico'' es vulgar (pene).', 'Falsos amigos', 'sustantivo'),
  ('concha-caparazon', 'concha (caparazón, nombre propio)', null, 'En España, caparazón de molusco o diminutivo de Concepción. Ojo: en Chile es muy vulgar (genitales femeninos).', 'Falsos amigos', 'sustantivo'),
  ('polla-vulg', 'polla (vulg., pene)', 'polla (lotería)', 'Falso amigo: en España es vulgar; en Chile es el nombre de la lotería.', 'Falsos amigos', 'sustantivo'),
  ('cachos-cuernos', 'cachos (cuernos, juv.)', 'cacho (problema), cachos (cuernos)', 'En Chile ''cacho'' es un problema o carga; ''cachos'', como en España, también son cuernos.', 'Falsos amigos', 'sustantivo'),
  ('pringar', 'pringar', null, 'Hacer el trabajo pesado o salir perjudicado; también mancharse.', 'Trabajo y estudio', 'verbo'),
  ('hacer-el-canelo', 'hacer el canelo', 'hacer el leso', 'Hacer el tonto o dejarse engañar.', 'Personas y tipos sociales', 'expresión verbal')
on conflict (slug) do nothing;
